title       = "lobsters"
baseURL     = "https://lobsters-cli.tamnd.com/"
description = "A command line for Lobste.rs."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/lobsters-cli"
